version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gacs-dashboard-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user_gacs
      DB_PASS: secret_password
      DB_NAME: host_gacs

  db:
    image: mariadb:10.11
    container_name: gacs-dashboard-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret_root_password
      MYSQL_DATABASE: host_gacs
      MYSQL_USER: user_gacs
      MYSQL_PASSWORD: secret_password
    volumes:
      - db_data:/var/lib/mysql
      # Map the WHOLE current directory to docker-entrypoint-initdb.d
      # MariaDB will automatically find database.sql inside it and import it
      - ./:/docker-entrypoint-initdb.d/

volumes:
  db_data:
